name: Familie Pfeiffer
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext/index.html
themeBGimage: https://template.pc-cdn.de/assets/bg-images/2560px-Milky_Way_Galaxy_As_Seen_From_Amphulaptsa_Base_Camp.jpg
impress: impressumps
since: 2018
