remote_theme: PfeifferChPT/pc-cdn-template
name: Familie Pfeiffer
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext/index.html
themeBGimage: https://template.pc-cdn.de/assets/bg-images/2560px-Milky_Way_Galaxy_As_Seen_From_Amphulaptsa_Base_Camp.jpg
impress: impressumps
author: Familie Pfeiffer
since: 2018

# Fonts:
Font1: RoadRage-Regular
Font2: Trispace

# hostcredits: GHP (githubpages), IDN (IONOS DeployNow), OHI (Own Server)
hostcredit: GHP
FAS: CSS
# FAS (Fontawesome): CSS (css File) JS (javascript) FASkit (Remote von kit.fontawesome.com)
